<?php

namespace BlogBundle\Entity\Repository;

/**
 * LevelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LevelsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLevels($title) {
        return $this->getEntityManager()
            ->createQuery("SELECT c FROM BlogBundle:LevelsTranslation c WHERE c.title LIKE '%$title%'")
            ->getResult();
    }

}
