<?php

namespace BlogBundle\Entity\Repository;

/**
 * PostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getReadAlso($id)
    {
        $query = $this->createQueryBuilder('p');
        $query->where("p.id != $id");
        $query->andWhere("p.category_id = 2");
        $posts = $query->getQuery()->getResult();

        return $posts;
    }
}