<?php

namespace UsersBundle\Entity\Repository;

/**
 * UsersLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersLogRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCntByMonth()
    {
        $begin_date = date('Y-1-1');
        $end_date = date('Y-12-31');

        $conn = $this->getEntityManager()->getConnection();
        $sql = "SELECT
                    EXTRACT(YEAR FROM f.creation) as y,
                    EXTRACT(MONTH FROM f.creation) as m,
                    count(*) as cnt
                FROM
                    (SELECT
                        creation,
                        count(distinct(user_ip))
                     FROM
                        users_log
                     GROUP BY
                        YEAR(creation),
                        MONTH(creation),
                        DAY(creation)
                    ) as f
                GROUP BY
                    YEAR(f.creation),
                    MONTH(f.creation)
                ";
        $cnt = $conn->prepare($sql);
        $cnt->execute();
        return $cnt->fetchAll();
    }

}
