<?php

namespace UsersBundle\Entity\Repository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUsers($word)
    {
        $result = $this->getEntityManager()
            ->createQuery(
                "SELECT u FROM UsersBundle:Users u WHERE
                          u.firstname LIKE '$word%' OR
                          u.lastname LIKE '$word%' OR
                          u.patronymic LIKE '$word%' OR
                          u.username LIKE '$word%' OR
                          u.email LIKE '$word%'
                          "
            )
            ->getResult();
        return $result;

    }

}
