imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: "@BlogBundle/Resources/config/services.yml" }
    - { resource: "@GalleryBundle/Resources/config/services.yml" }
    - { resource: "@MenuBundle/Resources/config/services.yml" }
    - { resource: "@PageBundle/Resources/config/services.yml" }
    - { resource: "@SitemapBundle/Resources/config/services.yml" }
    - { resource: "@UsersBundle/Resources/config/services.yml" }

parameters:
    locale: en

framework:
    #esi: ~
    translator: ~ #{ fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        container: '@service_container'
        youtube: '%youtube_api_key%'
    form_themes:
        - 'TetranzSelect2EntityBundle:Form:fields.html.twig'
# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        filters:
            oneLocale:
                class: A2lix\I18nDoctrineBundle\Doctrine\ORM\Filter\OneLocaleFilter
                enabled: true
        dql:
            numeric_functions:
                Rand: ContentBundle\Entity\DQL\RandFunction

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: UsersBundle\Entity\Users
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    profile:
      form:
        type: UsersBundle\Form\Type\ProfileFormType
    registration:
        form:
            type: UsersBundle\Form\Type\RegistrationFormType
        confirmation:
            from_email:
                address:        registration@example.com
                sender_name:    Demo Registration
            enabled:    true
    resetting:
        email:
            from_email:
                address:        noreply@yoursite.com
                sender_name:    No Reply

#JMSTranslationBundle Configuration
jms_i18n_routing:
    default_locale: %default_locale%
    locales: %locales%
    strategy: prefix_except_default

# a2lix translations
a2lix_i18n_doctrine:
    manager_registry: doctrine
a2lix_translation_form:
    locale_provider: default
    locales: %locales%
    default_locale: %default_locale%
    required_locales: %default_locale%
    manager_registry: doctrine
    templating: "A2lixTranslationFormBundle::default.html.twig"

# slug
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: MenuBundle:Default:knp_menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: true
    # the renderer to use, list is also available by default
    default_renderer: twig

knp_paginator:
    page_range: "%page_range%"       # default page range used in pagination control
    default_options:
        page_name: page              # page query parameter name
        sort_field_name: id          # sort field query parameter name
        sort_direction_name: desc    # sort direction query parameter name
        distinct: true               # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
        #pagination: KnpPaginatorBundle:Pagination:sliding.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

sonata_seo:
    encoding:         UTF-8
    page:
        title:            freeticket.loc
        default:          sonata.seo.page.default
        metas:
            name:
                keywords:             freeticket.loc
                description:          freeticket.loc
                robots:               freeticket.loc

            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                #'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       freeticket.loc
                'og:description':     freeticket.loc

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7

            charset:
                UTF-8:    ''

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
            #'xmlns:fb':           "http://www.facebook.com/2008/fbml"

liip_imagine:
    resolvers:
       default:
          web_path: ~
    filter_sets:
        cache: ~
        user_avatar_thumb:
            quality: 100
            filters:
                thumbnail: { size: [120, 120], mode: outbound }
        admin_thumb_index:
            quality: 100
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
        admin_thumb_create:
            quality: 100
            filters:
                thumbnail: { size: [100, 100], mode: outbound }
