security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: admin #fos_user_profile_show
                always_use_default_target_path: true
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: fos_user_security_logout
                target: fos_user_security_login
            logout:       true
            anonymous:    true

    access_control:
#    ANONIMUS
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#    ADMIN
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/admin/(.*?), role: ROLE_ADMIN }
        - { path: ^(.*?)/admin, role: ROLE_ADMIN }
        - { path: (.*?)/admin/(.*?)$, role: ROLE_ADMIN }
